default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: schedule_development

test:
  <<: *default
  database: schedule_test

production:
  <<: *default
  database: schedule_production
  username: schedule
  password: <%= ENV['schedule_DATABASE_PASSWORD'] %>
